apiVersion: eksctl.io/v1alpha5
        kind: ClusterConfig
        
        metadata:
          name: my-cluster
          region: eu-west-1
        
        nodeGroups:
          - name: group1
            instanceType: 
            desiredCapacity: 5
            volumeSize: 50
            ssh:
              allow: true
          - name: group2
            instanceType: 
            desiredCapacity: 2
            volumeSize: 100
            ssh:
              publicKeyPath: ~/.ssh/other.pub


    //$ eksctl create cluster -f config.yaml
