apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pithy-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pithy-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
