apiVersion: v1
kind: Service
metadata:
  name: pithy-service
spec:
  selector:
    app: pithy
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31000
